FROM ubuntu:14.04.5

MAINTAINER MadLabBrazil Team Maintainers "mesaque.s.silva@gmail.com"

ENV DEBIAN_FRONTEND noninteractive
ENV NGINX_PATH /usr/local/openresty/nginx/conf

RUN apt-get update \
	&& apt-get -y install libreadline-dev libncurses5-dev libpcre3-dev \
    libssl-dev perl make build-essential wget zlib1g-dev libpcre3 unzip curl

RUN /usr/bin/wget https://openresty.org/download/openresty-1.11.2.2.tar.gz && tar -xzf openresty-1.11.2.2.tar.gz
RUN cd  /openresty-1.11.2.2 && /usr/bin/wget https://github.com/pagespeed/ngx_pagespeed/archive/release-1.11.33.4-beta.zip \
&& /usr/bin/wget https://www.openssl.org/source/openssl-1.0.2j.tar.gz \
&& tar -xzf openssl-1.0.2j.tar.gz \
&& unzip -x release-1.11.33.4-beta.zip \
&& cd ngx_pagespeed-release-1.11.33.4-beta \
&& /usr/bin/wget https://dl.google.com/dl/page-speed/psol/1.11.33.4.tar.gz \
&& tar -xzf 1.11.33.4.tar.gz

RUN cd /openresty-1.11.2.2 \
&& /usr/bin/wget http://labs.frickle.com/files/ngx_cache_purge-2.3.tar.gz \
&& tar -xzf ngx_cache_purge-2.3.tar.gz

RUN cd /openresty-1.11.2.2 \
&& /openresty-1.11.2.2/configure \
--add-module=/openresty-1.11.2.2/ngx_pagespeed-release-1.11.33.4-beta \
--add-module=/openresty-1.11.2.2/ngx_cache_purge-2.3 \
--with-http_stub_status_module \
--with-http_v2_module --with-openssl=/openresty-1.11.2.2/openssl-1.0.2j \
--with-ipv6 \
&& /usr/bin/make && /usr/bin/make install

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /usr/local/openresty/nginx/logs/access.log \
	&& ln -sf /dev/stderr /usr/local/openresty/nginx/logs/error.log

RUN ln -s /usr/local/openresty/nginx/sbin/nginx /usr/bin/nginx

EXPOSE 80 443

WORKDIR $NGINX_PATH/
CMD ["/usr/local/openresty/nginx/sbin/nginx", "-g", "daemon off;"]
